In [10]:
#imports
import pandas as pd

In [3]:
import json
with open('/Users/thoma/.secret/yelp_api.json') as f:
    login = json.load(f)
login.keys()

dict_keys(['client-id', 'api-key'])

In [4]:
# import the YelpAPI Class
from yelpapi import YelpAPI
# Create an instance with your key
yelp_api = YelpAPI(login['api-key'], timeout_s=5.0)
yelp_api

In [5]:
help(yelp_api.search_query)

Help on method search_query in module yelpapi.yelpapi:

search_query(**kwargs) method of yelpapi.yelpapi.YelpAPI instance
    Query the Yelp Search API.

    documentation: https://www.yelp.com/developers/documentation/v3/business_search

    required parameters:
        * one of either:
            * location - text specifying a location to search for
            * latitude and longitude

In [6]:
# use our yelp_api variable's search_query method to perform our API call
search_results = yelp_api.search_query(location='Baltimore, MD,21202',
                                       term='Crab Cakes')
print(type(search_results))
search_results.keys()

<class 'dict'>

dict_keys(['businesses', 'total', 'region'])

In [7]:
search_results['total']

441

In [11]:
biz = pd.DataFrame(search_results['businesses'])
biz.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,D9A33FM394q99o4QtK5YwA,faidleys-seafood-baltimore-3,Faidley's Seafood,https://s3-media3.fl.yelpcdn.com/bphoto/8j3ynZ...,False,https://www.yelp.com/biz/faidleys-seafood-balt...,1229,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.0,"{'latitude': 39.291696, 'longitude': -76.62224}",[delivery],$$,"{'address1': '203 N Paca St', 'address2': '', ...",+14107274898,(410) 727-4898,1349.560720
1,ieS_5zqxDHcWMCm8BKUYbg,thames-street-oyster-house-baltimore,Thames Street Oyster House,https://s3-media1.fl.yelpcdn.com/bphoto/9hGjo5...,False,https://www.yelp.com/biz/thames-street-oyster-...,2836,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.5,"{'latitude': 39.28214, 'longitude': -76.59162}",[delivery],$$$,"{'address1': '1728 Thames St', 'address2': '',...",+14434497726,(443) 449-7726,2090.712792

In [12]:
## total number of matching businesses
search_results['total']

441

In [13]:
## how many businesses in our results
len(search_results['businesses'])

20

In [14]:
# add offset to our original api call
search_results = yelp_api.search_query(location='Baltimore, MD,21202',
                                       term='Crab Cakes',
                                       offset = 20)

In [15]:
biz20 = pd.DataFrame(search_results['businesses'])
biz20.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,VLGdENTqjFJuCjg1SbW7_g,nicks-fish-house-baltimore,Nicks Fish House,https://s3-media3.fl.yelpcdn.com/bphoto/xMvMJ9...,False,https://www.yelp.com/biz/nicks-fish-house-balt...,927,"[{'alias': 'seafood', 'title': 'Seafood'}]",4.0,"{'latitude': 39.26036, 'longitude': -76.61421}",[delivery],$$,"{'address1': '2600 Insulator Dr', 'address2': ...",+14103474123,(410) 347-4123,3984.496569
1,TPQmNAM2g1vmm2xCfhyEJw,pratt-street-ale-house-baltimore,Pratt Street Ale House,https://s3-media4.fl.yelpcdn.com/bphoto/DA0K3G...,False,https://www.yelp.com/biz/pratt-street-ale-hous...,837,"[{'alias': 'pubs', 'title': 'Pubs'}, {'alias':...",3.5,"{'latitude': 39.2865982055664, 'longitude': -7...","[pickup, delivery]",$$,"{'address1': '206 W Pratt St', 'address2': '',...",+14102448900,(410) 244-8900,1403.278532

In [16]:
## concatenate the previous results and new results. 
businesses = pd.concat([biz, biz20],
                      ignore_index=True)
display(businesses.head(3), businesses.tail(3))

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,D9A33FM394q99o4QtK5YwA,faidleys-seafood-baltimore-3,Faidley's Seafood,https://s3-media3.fl.yelpcdn.com/bphoto/8j3ynZ...,False,https://www.yelp.com/biz/faidleys-seafood-balt...,1229,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.0,"{'latitude': 39.291696, 'longitude': -76.62224}",[delivery],$$,"{'address1': '203 N Paca St', 'address2': '', ...",+14107274898,(410) 727-4898,1349.560720
1,ieS_5zqxDHcWMCm8BKUYbg,thames-street-oyster-house-baltimore,Thames Street Oyster House,https://s3-media1.fl.yelpcdn.com/bphoto/9hGjo5...,False,https://www.yelp.com/biz/thames-street-oyster-...,2836,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.5,"{'latitude': 39.28214, 'longitude': -76.59162}",[delivery],$$$,"{'address1': '1728 Thames St', 'address2': '',...",+14434497726,(443) 449-7726,2090.712792
2,u65W69AhbjUlvJJBkEhGNQ,miss-shirleys-cafe-baltimore-9,Miss Shirley's Cafe,https://s3-media2.fl.yelpcdn.com/bphoto/Guq6JM...,False,https://www.yelp.com/biz/miss-shirleys-cafe-ba...,3053,"[{'alias': 'breakfast_brunch', 'title': 'Break...",4.0,"{'latitude': 39.2870995, 'longitude': -76.6053...",[delivery],$$,"{'address1': '750 E Pratt St', 'address2': '',...",+14105285373,(410) 528-5373,1028.736468

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
37,0HAy_fw3WrsiG_5lRVObTw,captain-james-crab-house-baltimore,Captain James Crab House,https://s3-media4.fl.yelpcdn.com/bphoto/B3MLVa...,False,https://www.yelp.com/biz/captain-james-crab-ho...,401,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",3.5,"{'latitude': 39.28346, 'longitude': -76.58633}",[delivery],$$,"{'address1': '2121 Aliceanna St', 'address2': ...",+14103278600,(410) 327-8600,2343.033653
38,yllFleLLvGVm9dZ-dRFZHg,papi-cuisine-baltimore,Papi Cuisine,https://s3-media2.fl.yelpcdn.com/bphoto/uBoDyK...,False,https://www.yelp.com/biz/papi-cuisine-baltimor...,436,"[{'alias': 'cocktailbars', 'title': 'Cocktail ...",4.0,"{'latitude': 39.26920460905755, 'longitude': -...",[delivery],$$$,"{'address1': '2 E Wells St', 'address2': 'Ste ...",+16672051838,(667) 205-1838,3026.776496
39,19NqOlADe8wHXWtx5sWRtQ,busboys-and-poets-baltimore-baltimore,Busboys and Poets - Baltimore,https://s3-media2.fl.yelpcdn.com/bphoto/jSYlOA...,False,https://www.yelp.com/biz/busboys-and-poets-bal...,164,"[{'alias': 'newamerican', 'title': 'American (...",4.0,"{'latitude': 39.32772376459962, 'longitude': -...","[pickup, delivery]",$$,"{'address1': '3224 St Paul St', 'address2': No...",+14104977114,(410) 497-7114,3584.688707